version: '3.8'

services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mem
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: always
    depends_on:
      - bonus-api
      - bonus-gateway

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"  # Web UI
      - "4317:4317"    # OTLP gRPC
      - "4318:4318"    # OTLP HTTP
      - "14268:14268"  # Zipkin-compatible API
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    restart: unless-stopped

  bonus-gateway:
    restart: always
    build:
      context: ./bonus_gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - BONUS_API_HOST=http://bonus-api:8081
      - MANAGEMENT_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans

  bonus-api:
    restart: always
    build:
      context: ./bonus_api
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - MANAGEMENT_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans

volumes:
  grafana_data: