spring:
  datasource:
    url: ${BONUS_REFERRAL_DB_URL:jdbc:postgresql://localhost:5433/bonus-referral}
    username: ${BONUS_REFERRAL_DB_USERNAME:bonus-referral}
    password: ${BONUS_REFERRAL_DB_PASSWORD:D3v!@#bonus-ref#1}
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 30000
      idleTimeout: 300000
      maxLifetime: 1800000
      maximum-pool-size: 50
      leak-detection-threshold: 5000
      minimum-idle: 5
      initialization-fail-timeout: 5000
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect