server:
  port: ${BONUS_API_PORT:8081}
spring:
  application:
    name: bonus_api

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  tracing:
    sampling:
      probability: 1.0
  metrics:
    export:
      prometheus:
        enabled: true
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}
