spring:
  application:
    name: bonus_gateway
  cloud:
    gateway:
      routes:
        - id: api-service
          uri: ${BONUS_API_HOST:http://localhost:8081}
          predicates:
            - Path=/api/v1/**
          filters:
            - StripPrefix=2

        - id: payment-service
          uri: ${BONUS_PAYMENT_HOST:http://localhost:8082}
          predicates:
            - Path=/api/v1/payment/**
          filters:
            - StripPrefix=2

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  tracing:
    sampling:
      probability: 1.0
  metrics:
    export:
      prometheus:
        enabled: true
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}
